<!DOCTYPE html>

<?php
?>
<html>
    <head>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
        <meta charset="utf-8">
        <title>Simple Markers</title>
        <style>
            /* Always set the map height explicitly to define the size of the div
             * element that contains the map. */
            #map {
                height: 100%;
            }
            /* Optional: Makes the sample page fill the window. */
            html, body {
                height: 100%;
                margin: 0;
                padding: 0;
            }
        </style>
    </head>
    <body>
        <div id="map"></div>
        <script>

            function initMap() {
                var myLatLngStart = {lat: <?php echo $start[0]; ?>, lng: <?php echo $start[1] ?>};
                var myLatLngResult = {lat: <?php echo $near[0] ?>, lng: <?php echo $near[1] ?>};

                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 12,
                    center: myLatLngStart
                });

                var marker = new google.maps.Marker({
                    position: myLatLngStart,
                    map: map,
                    title: 'Choosen GPS position',
                    icon: {
                        url: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"
                    }
                });

                var marker = new google.maps.Marker({
                    position: myLatLngResult,
                    map: map,
                    title: "<?php echo "$name" ?>"
                });

            }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBev6P8BEdL-i1NpJV5uHr9VTonYmbEfQE&callback=initMap"
        async defer></script>
    </body>
</html>